import { NovaCommand, NovaEnvironment } from './novaTypes';

export const NOVA_ENVIRONMENTS: Record<NovaEnvironment, { name: string; label: string; url: string; badge: string; color: string }> = {
  platform: {
    name: 'NOVA Platform',
    label: 'HQ & Market',
    url: 'https://nova-platfrom.vercel.app',
    badge: 'HQ',
    color: 'from-cyan-400 to-blue-500',
  },
  mind: {
    name: 'NOVA Mind',
    label: 'Academy & Faculties',
    url: 'https://nova-mindset.vercel.app',
    badge: 'MIND',
    color: 'from-blue-400 to-indigo-500',
  },
  producer: {
    name: 'NOVA Producer',
    label: 'Studio & War Room',
    url: 'https://nova-company.vercel.app',
    badge: 'PRODUCER',
    color: 'from-violet-400 to-purple-500',
  },
  artlabs: {
    name: 'NOVA Art Labs',
    label: 'Visual & Media Gen',
    url: 'https://nova-artlabs.vercel.app',
    badge: 'ART LABS',
    color: 'from-fuchsia-400 to-pink-500',
  },
  community: {
    name: 'NOVA Community',
    label: 'Syndicate & Arena',
    url: 'https://novacommunity.vercel.app',
    badge: 'COMMUNITY',
    color: 'from-amber-400 to-orange-500',
  },
};

export const GLOBAL_COMMANDS: NovaCommand[] = [
  // 1. Navigation Commands
  {
    id: 'nav.home',
    label: 'Go to NOVA Platform (HQ)',
    subtitle: 'Sovereign Marketplace, Asset Catalog, Web3 Profile',
    group: 'Navigate',
    environment: 'platform',
    shortcut: 'G H',
    url: 'https://nova-platfrom.vercel.app',
    badge: 'HQ',
    keywords: ['home', 'platform', 'market', 'store', 'hq', 'assets'],
  },
  {
    id: 'nav.mind',
    label: 'Go to NOVA Mind (Academy)',
    subtitle: '7 Frontier Faculties, Simulator Interaktif, Diagnostics',
    group: 'Navigate',
    environment: 'mind',
    shortcut: 'G M',
    url: 'https://nova-mindset.vercel.app',
    badge: 'MIND',
    keywords: ['mind', 'learn', 'academy', 'faculties', 'simulator', 'quiz', 'course'],
  },
  {
    id: 'nav.producer',
    label: 'Go to NOVA Producer (Studio)',
    subtitle: 'AI War Room, 7 Pilar Produksi, FastTrack Prompting',
    group: 'Navigate',
    environment: 'producer',
    shortcut: 'G P',
    url: 'https://nova-company.vercel.app',
    badge: 'PRODUCER',
    keywords: ['producer', 'war room', 'fasttrack', 'studio', 'prompts', 'council', 'production'],
  },
  {
    id: 'nav.artlabs',
    label: 'Go to NOVA Art Labs (Visual Studio)',
    subtitle: 'Haute Couture Logo Designer, Video Animation, Storyboard',
    group: 'Navigate',
    environment: 'artlabs',
    shortcut: 'G A',
    url: 'https://nova-artlabs.vercel.app',
    badge: 'ART LABS',
    keywords: ['art', 'artlabs', 'logo', 'design', 'video', 'animation', 'storyboard', 'image'],
  },
  {
    id: 'nav.community',
    label: 'Go to NOVA Community (Syndicate)',
    subtitle: 'Private Signal Feeds, The Arena Leaderboard, OTC Escrow',
    group: 'Navigate',
    environment: 'community',
    shortcut: 'G C',
    url: 'https://novacommunity.vercel.app',
    badge: 'COMMUNITY',
    keywords: ['community', 'syndicate', 'arena', 'leaderboard', 'otc', 'deals', 'signals'],
  },

  // 2. Quick Actions
  {
    id: 'action.mind_simulator',
    label: 'Mulai Interactive Systems Simulator',
    subtitle: 'Uji stress-test model sistem AI, trading, dan energi',
    group: 'Quick Actions',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app/simulation',
    badge: 'SIMULATOR',
    keywords: ['simulate', 'sandbox', 'test', 'interactive', 'terminal'],
  },
  {
    id: 'action.producer_war_room',
    label: 'Buka AI Executive War Room',
    subtitle: 'Konsultasi arsitektur multi-agent dan dewan eksekutif',
    group: 'Quick Actions',
    environment: 'producer',
    url: 'https://nova-company.vercel.app',
    badge: 'WAR ROOM',
    keywords: ['war room', 'executive', 'council', 'ai agent'],
  },
  {
    id: 'action.art_logo_designer',
    label: 'Buat Logo Haute Couture Baru',
    subtitle: 'Generator logo AI presisi tinggi dengan mockup 3D',
    group: 'Quick Actions',
    environment: 'artlabs',
    url: 'https://nova-artlabs.vercel.app',
    badge: 'LOGO AI',
    keywords: ['create logo', 'new logo', 'vector', 'brand'],
  },
  {
    id: 'action.community_arena',
    label: 'Cek Live The Arena Leaderboard',
    subtitle: 'Pantau volume transaksi tervalidasi dan peringkat guild',
    group: 'Quick Actions',
    environment: 'community',
    url: '#',
    badge: 'ARENA',
    keywords: ['arena', 'leaderboard', 'ranking', 'revenue'],
  },

  // 3. Faculties & Courses (NOVA Mind)
  {
    id: 'faculty.ai_mastery',
    label: 'Fakultas 1: AI Mastery & Agent Swarms',
    subtitle: 'Prompt engineering, Claude/Gemini API, RAG, Autonomous Agents',
    group: 'Faculties & Courses',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app',
    badge: 'AI',
    keywords: ['ai', 'agent', 'rag', 'llm', 'prompt', 'gpt', 'claude'],
  },
  {
    id: 'faculty.deep_it',
    label: 'Fakultas 2: Deep IT & Cyber Architecture',
    subtitle: 'Distributed systems, Cloud concurrency, Cryptographic security',
    group: 'Faculties & Courses',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app',
    badge: 'IT',
    keywords: ['it', 'code', 'server', 'kubernetes', 'cloud', 'architecture'],
  },
  {
    id: 'faculty.quant_finance',
    label: 'Fakultas 3: Quant Finance & Modern Economics',
    subtitle: 'Asymmetric leverage, Capital allocation, DeFi mechanics',
    group: 'Faculties & Courses',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app',
    badge: 'FINANCE',
    keywords: ['quant', 'finance', 'crypto', 'saham', 'economics', 'trading'],
  },
  {
    id: 'faculty.energy_matrix',
    label: 'Fakultas 4: Energy Matrix & Grid Physics',
    subtitle: 'Renewables, Battery density, Nuclear, Grid optimization',
    group: 'Faculties & Courses',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app',
    badge: 'ENERGY',
    keywords: ['energy', 'battery', 'solar', 'grid', 'physics'],
  },
  {
    id: 'faculty.biotech',
    label: 'Fakultas 5: BioTech & Longevity Engineering',
    subtitle: 'CRISPR, Cellular biomarkers, Synthetic biology, Health metrics',
    group: 'Faculties & Courses',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app',
    badge: 'BIOTECH',
    keywords: ['biotech', 'longevity', 'crispr', 'biology', 'health'],
  },
  {
    id: 'faculty.mental_models',
    label: 'Fakultas 6: Sovereign Mindset & Mental Models',
    subtitle: 'Outsmart the System, The Zero Emotion, First-principles thinking',
    group: 'Faculties & Courses',
    environment: 'mind',
    url: 'https://nova-mindset.vercel.app',
    badge: 'MINDSET',
    keywords: ['mindset', 'stoic', 'zero emotion', 'outsmart', 'rational'],
  },

  // 4. Market & Digital Assets (NOVA Platform)
  {
    id: 'asset.godot_gdscript',
    label: 'Godot 4 Architecture Mastery & GDScript 2.0',
    subtitle: 'Asset produksi game mandiri berskala komersial',
    group: 'Market & Assets',
    environment: 'platform',
    url: 'https://nova-platfrom.vercel.app/store',
    badge: 'GDScript',
    keywords: ['godot', 'game', 'gdscript', 'engine', 'steam'],
  },
  {
    id: 'asset.nextjs_saas',
    label: 'Next.js 14 Sovereign SaaS Enterprise Kit',
    subtitle: 'Boilerplate production-ready dengan Supabase & Stripe/QRIS',
    group: 'Market & Assets',
    environment: 'platform',
    url: 'https://nova-platfrom.vercel.app/store',
    badge: 'SaaS Kit',
    keywords: ['nextjs', 'saas', 'boilerplate', 'starter', 'react'],
  },
  {
    id: 'asset.outsmart_book',
    label: 'Outsmart the System (Core Playbook)',
    subtitle: 'Blueprint berpikir asimetris dan navigasi sistem modern',
    group: 'Market & Assets',
    environment: 'platform',
    url: 'https://nova-platfrom.vercel.app/store',
    badge: 'Playbook',
    keywords: ['outsmart', 'system', 'playbook', 'ebook', 'unicorn'],
  },
];
